steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/mentors-mantra-gen/gcr.io/mentors-mantra-base:latest', '-t', 'gcr.io/mentors-mantra-gen/mentors-mantra-base:latest', '-f', 'Dockerfile.base', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mentors-mantra-gen/mentors-mantra-base:latest']
timeout: '3600s'
options:
  machineType: 'E2_HIGHCPU_8'
